dist: trusty
language: java
sudo: required
jdk: oraclejdk11

install: mvn clean install test -U -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true

cache:
  directories:
  - $HOME/.m2
