language: java

dist: trusty
sudo: false

# Get latest install-jdk.sh script
before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

install: ./install-jdk.sh -F 10 -C

script:
  - mvn test -B

cache:
  directories:
  - $HOME/.m2
