############################################################
#   _____                        _        ____        _    #
#  / ____|                      | |      |  _ \      | |   #
# | |     __ _ ___  ___ __ _  __| | ___  | |_) | ___ | |_  #
# | |    / _` / __|/ __/ _` |/ _` |/ _ \ |  _ < / _ \| __| #
# | |___| (_| \__ \ (_| (_| | (_| |  __/ | |_) | (_) | |_  #
#  \_____\__,_|___/\___\__,_|\__,_|\___| |____/ \___/ \__| #
#                                                          #
# This is the config for Cascade Bot. Each field is        #
# commented with its usage.                                #
#                                                          #
# Fields marked with "# REQUIRED" need to be entered for   #
# the bot to start.                                        #
############################################################


bot_id:
token:



