name: cascade-changelog

on:
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: CascadeBot/Changelog-Action@v1
      with:
        discordPreviewWebhook: ${{ secrets.discordPreviewWebhook }}
        discordPublishWebhook: ${{ secrets.discordPublishWebhook }}
        authorisedUsers: mrjvs,binaryoverload,weeryan17
